apiVersion: v1
kind: Service
metadata:
  name: smartlink
  labels:
    app: smartlink
spec:
  type: {{ .Values.service.type }}
  selector:
    app: smartlink
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}